<a href="https://colab.research.google.com/github/RaniellyPatricia/predicao-abandono-escolar-mg/blob/main/notebooks/01_coleta_e_descricao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Coleta e Descrição dos Dados

## Predição do Abandono Escolar nos Municípios de Minas Gerais

Este notebook tem como objetivo realizar a leitura inicial, a identificação da estrutura e a descrição das bases públicas do INEP utilizadas no projeto.

Nesta etapa ainda não serão aplicados filtros nem tratamentos definitivos. Primeiro serão verificadas as abas, colunas, dimensões, tipos de dados, valores ausentes e possíveis duplicidades.

## 1. Nível Socioeconômico — INSE

Nesta seção será realizada a inspeção inicial da base municipal do Indicador de Nível Socioeconômico de 2023.

Serão analisadas a estrutura da planilha, as abas disponíveis, as dimensões, as colunas, os tipos de dados, os valores ausentes e possíveis duplicidades. Nesta etapa, a base ainda não será filtrada ou modificada.

In [18]:
import pandas as pd
import requests
from io import BytesIO

url_inse = (
    "https://raw.githubusercontent.com/"
    "RaniellyPatricia/predicao-abandono-escolar-mg/"
    "main/data/raw/2023/inse/INSE_2023_municipios.xlsx"
)

resposta = requests.get(url_inse)
resposta.raise_for_status()

print("Tamanho baixado:", len(resposta.content), "bytes")
print("Assinatura do arquivo:", resposta.content[:4])

arquivo_inse = pd.ExcelFile(BytesIO(resposta.content))

arquivo_inse.sheet_names

Tamanho baixado: 11483563 bytes
Assinatura do arquivo: b'PK\x03\x04'

['INSE_MUN_2023', 'Dicionário']

In [19]:
df_inse = pd.read_excel(
    BytesIO(resposta.content),
    sheet_name="INSE_MUN_2023"
)

print("Quantidade de linhas:", df_inse.shape[0])
print("Quantidade de colunas:", df_inse.shape[1])

df_inse.head()

Quantidade de linhas: 125741
Quantidade de colunas: 19

,NU_ANO_SAEB,CO_UF,SG_UF,NO_UF,CO_MUNICIPIO,NO_MUNICIPIO,TP_TIPO_REDE,TP_LOCALIZACAO,TP_CAPITAL,QTD_ALUNOS_INSE,MEDIA_INSE,PC_NIVEL_1,PC_NIVEL_2,PC_NIVEL_3,PC_NIVEL_4,PC_NIVEL_5,PC_NIVEL_6,PC_NIVEL_7,PC_NIVEL_8
0,2023,11,RO,Rondônia,1100122,Ji-Paraná,2,1,2,3258,5.0083,0.16,6.71,18.43,25.63,24.64,14.36,9.18,0.89
1,2023,11,RO,Rondônia,1101559,Teixeirópolis,0,2,2,19,4.8242,5.26,NaN,21.05,31.58,26.32,15.79,NaN,NaN
2,2023,11,RO,Rondônia,1100205,Porto Velho,3,1,1,3610,4.8843,0.57,11.59,20.00,26.07,20.78,12.87,7.11,1.02
3,2023,11,RO,Rondônia,1101005,Governador Jorge Teixeira,5,2,2,46,4.8115,0.00,6.59,21.59,39.09,19.77,8.64,4.32,NaN
4,2023,11,RO,Rondônia,1100205,Porto Velho,2,1,1,9541,5.0505,0.30,7.89,17.27,23.41,23.09,16.37,10.45,1.23

In [20]:
print("Colunas da base INSE:")

for coluna in df_inse.columns:
    print(coluna)
df_inse.dtypes

Colunas da base INSE:
NU_ANO_SAEB
CO_UF
SG_UF
NO_UF
CO_MUNICIPIO
NO_MUNICIPIO
TP_TIPO_REDE
TP_LOCALIZACAO
TP_CAPITAL
QTD_ALUNOS_INSE
MEDIA_INSE
PC_NIVEL_1
PC_NIVEL_2
PC_NIVEL_3
PC_NIVEL_4
PC_NIVEL_5
PC_NIVEL_6
PC_NIVEL_7
PC_NIVEL_8

NU_ANO_SAEB          int64
CO_UF                int64
SG_UF               object
NO_UF               object
CO_MUNICIPIO         int64
NO_MUNICIPIO        object
TP_TIPO_REDE         int64
TP_LOCALIZACAO       int64
TP_CAPITAL           int64
QTD_ALUNOS_INSE      int64
MEDIA_INSE         float64
PC_NIVEL_1         float64
PC_NIVEL_2         float64
PC_NIVEL_3         float64
PC_NIVEL_4         float64
PC_NIVEL_5         float64
PC_NIVEL_6         float64
PC_NIVEL_7         float64
PC_NIVEL_8         float64
dtype: object

In [21]:
resumo_nulos_inse = pd.DataFrame({
    "quantidade_nulos": df_inse.isna().sum(),
    "percentual_nulos": (df_inse.isna().mean() * 100).round(2)
})

resumo_nulos_inse

                 quantidade_nulos  percentual_nulos
NU_ANO_SAEB                     0              0.00
CO_UF                           0              0.00
SG_UF                           0              0.00
NO_UF                           0              0.00
CO_MUNICIPIO                    0              0.00
NO_MUNICIPIO                    0              0.00
TP_TIPO_REDE                    0              0.00
TP_LOCALIZACAO                  0              0.00
TP_CAPITAL                      0              0.00
QTD_ALUNOS_INSE                 0              0.00
MEDIA_INSE                    890              0.71
PC_NIVEL_1                     85              0.07
PC_NIVEL_2                   4460              3.55
PC_NIVEL_3                   1612              1.28
PC_NIVEL_4                    520              0.41
PC_NIVEL_5                    774              0.62
PC_NIVEL_6                   2950              2.35
PC_NIVEL_7                   7811              6.21
PC_NIVEL_8                  42414             33.73

In [22]:
quantidade_duplicadas_inse = df_inse.duplicated().sum()
print("Quantidade de linhas duplicadas:", quantidade_duplicadas_inse)

Quantidade de linhas duplicadas: 54165

In [23]:
registros_duplicados_inse = df_inse[
    df_inse.duplicated(keep=False)
].copy()

print(
    "Total de registros envolvidos em duplicidades:",
    registros_duplicados_inse.shape[0]
)

registros_duplicados_inse.head(10)

Total de registros envolvidos em duplicidades: 63034

,NU_ANO_SAEB,CO_UF,SG_UF,NO_UF,CO_MUNICIPIO,NO_MUNICIPIO,TP_TIPO_REDE,TP_LOCALIZACAO,TP_CAPITAL,QTD_ALUNOS_INSE,MEDIA_INSE,PC_NIVEL_1,PC_NIVEL_2,PC_NIVEL_3,PC_NIVEL_4,PC_NIVEL_5,PC_NIVEL_6,PC_NIVEL_7,PC_NIVEL_8
0,2023,11,RO,Rondônia,1100122,Ji-Paraná,2,1,2,3258,5.0083,0.16,6.71,18.43,25.63,24.64,14.36,9.18,0.89
2,2023,11,RO,Rondônia,1100205,Porto Velho,3,1,1,3610,4.8843,0.57,11.59,20.00,26.07,20.78,12.87,7.11,1.02
4,2023,11,RO,Rondônia,1100205,Porto Velho,2,1,1,9541,5.0505,0.30,7.89,17.27,23.41,23.09,16.37,10.45,1.23
10,2023,11,RO,Rondônia,1100072,Corumbiara,3,2,2,26,4.8232,0.00,3.92,19.17,53.38,15.69,3.92,NaN,3.92
12,2023,11,RO,Rondônia,1100015,Alta Floresta D'Oeste,2,1,2,480,4.9806,0.23,10.35,17.03,24.31,23.10,13.52,10.14,1.31
14,2023,11,RO,Rondônia,1100122,Ji-Paraná,2,1,2,3258,5.0083,0.16,6.71,18.43,25.63,24.64,14.36,9.18,0.89
16,2023,11,RO,Rondônia,1100205,Porto Velho,2,1,1,9541,5.0505,0.30,7.89,17.27,23.41,23.09,16.37,10.45,1.23
18,2023,11,RO,Rondônia,1100122,Ji-Paraná,2,1,2,3258,5.0083,0.16,6.71,18.43,25.63,24.64,14.36,9.18,0.89
19,2023,11,RO,Rondônia,1100049,Cacoal,2,1,2,1813,5.0218,0.28,7.32,17.01,26.28,23.55,15.89,8.88,0.80
22,2023,11,RO,Rondônia,1100015,Alta Floresta D'Oeste,3,1,2,240,5.0306,0.00,6.27,17.54,29.45,23.42,14.68,7.19,1.45

In [24]:
frequencia_duplicatas_inse = (
    df_inse
    .value_counts(dropna=False)
    .reset_index(name="FREQUENCIA")
)

frequencia_duplicatas_inse = frequencia_duplicatas_inse[
    frequencia_duplicatas_inse["FREQUENCIA"] > 1
].sort_values(
    by="FREQUENCIA",
    ascending=False
)

frequencia_duplicatas_inse.head(10)

,NU_ANO_SAEB,CO_UF,SG_UF,NO_UF,CO_MUNICIPIO,NO_MUNICIPIO,TP_TIPO_REDE,TP_LOCALIZACAO,TP_CAPITAL,QTD_ALUNOS_INSE,MEDIA_INSE,PC_NIVEL_1,PC_NIVEL_2,PC_NIVEL_3,PC_NIVEL_4,PC_NIVEL_5,PC_NIVEL_6,PC_NIVEL_7,PC_NIVEL_8,FREQUENCIA
0,2023,35,SP,São Paulo,3550308,São Paulo,2,1,1,171332,5.1512,0.41,5.48,13.23,23.64,25.28,18.60,12.21,1.14,1121
1,2023,33,RJ,Rio de Janeiro,3304557,Rio de Janeiro,3,1,1,80160,4.8607,0.88,10.09,20.30,28.19,21.73,11.77,6.36,0.69,947
2,2023,35,SP,São Paulo,3550308,São Paulo,3,1,1,70814,5.0653,0.65,6.97,14.78,24.69,24.80,16.73,10.45,0.93,552
3,2023,53,DF,Distrito Federal,5300108,Brasília,2,1,1,61528,5.3384,0.27,4.10,10.14,19.73,24.48,20.55,17.85,2.88,480
4,2023,29,BA,Bahia,2927408,Salvador,3,1,1,16910,4.5461,2.23,18.67,27.55,27.48,14.55,5.96,3.09,0.47,287
5,2023,23,CE,Ceará,2304400,Fortaleza,3,1,1,35105,4.5944,1.28,17.64,27.50,27.26,15.59,7.19,3.25,0.29,281
6,2023,13,AM,Amazonas,1302603,Manaus,3,1,1,28542,4.8092,0.87,12.89,22.07,26.57,19.35,10.73,6.60,0.92,271
7,2023,33,RJ,Rio de Janeiro,3304557,Rio de Janeiro,2,1,1,28238,4.8396,1.27,11.95,19.51,26.72,21.05,12.05,6.77,0.67,248
8,2023,13,AM,Amazonas,1302603,Manaus,2,1,1,42619,4.9518,0.73,10.81,18.96,24.70,20.30,12.97,10.01,1.53,223
9,2023,26,PE,Pernambuco,2611606,Recife,3,1,1,11171,4.6294,1.17,14.47,28.41,29.33,16.48,6.81,3.00,0.34,217

### Diagnóstico das duplicidades

Foram encontradas 54.165 ocorrências duplicadas, considerando como duplicada toda linha idêntica a uma ocorrência anterior.

No total, 63.034 registros estão envolvidos em grupos de duplicidade. Após considerar apenas uma ocorrência de cada linha, a base possui 71.576 registros únicos.

Algumas linhas apresentam frequência muito elevada, chegando a 1.121 repetições de um mesmo registro.

Como todas as 19 variáveis são idênticas nesses casos, as ocorrências foram classificadas como duplicidades exatas. A remoção será realizada posteriormente, na etapa de pré-processamento, mantendo a base original inalterada.

In [25]:
df_inse_tratado = df_inse.copy()

df_inse_tratado = df_inse_tratado[
    df_inse_tratado["SG_UF"] == "MG"
].copy()

print("Linhas da base original:", len(df_inse))
print("Linhas de Minas Gerais:", len(df_inse_tratado))

df_inse_tratado.head()

Linhas da base original: 125741
Linhas de Minas Gerais: 14671

,NU_ANO_SAEB,CO_UF,SG_UF,NO_UF,CO_MUNICIPIO,NO_MUNICIPIO,TP_TIPO_REDE,TP_LOCALIZACAO,TP_CAPITAL,QTD_ALUNOS_INSE,MEDIA_INSE,PC_NIVEL_1,PC_NIVEL_2,PC_NIVEL_3,PC_NIVEL_4,PC_NIVEL_5,PC_NIVEL_6,PC_NIVEL_7,PC_NIVEL_8
56381,2023,31,MG,Minas Gerais,3137007,Ladainha,5,0,2,393,4.4330,5.05,25.98,23.45,19.31,16.10,6.89,2.95,0.26
56382,2023,31,MG,Minas Gerais,3137007,Ladainha,6,1,2,276,4.3366,6.23,28.93,24.16,17.19,15.47,5.91,1.73,0.37
56383,2023,31,MG,Minas Gerais,3137007,Ladainha,5,1,2,276,4.3366,6.23,28.93,24.16,17.19,15.47,5.91,1.73,0.37
56384,2023,31,MG,Minas Gerais,3137007,Ladainha,5,2,2,117,4.6678,2.16,18.78,21.73,24.46,17.65,9.29,5.93,NaN
56385,2023,31,MG,Minas Gerais,3137007,Ladainha,3,2,2,117,4.6678,2.16,18.78,21.73,24.46,17.65,9.29,5.93,NaN

In [26]:
linhas_antes = len(df_inse_tratado)

df_inse_tratado = df_inse_tratado.drop_duplicates().copy()

linhas_depois = len(df_inse_tratado)

print("Linhas antes:", linhas_antes)
print("Linhas depois:", linhas_depois)
print("Duplicidades removidas:", linhas_antes - linhas_depois)

Linhas antes: 14671
Linhas depois: 10249
Duplicidades removidas: 4422

In [27]:
df_inse_tratado = df_inse_tratado[
    (df_inse_tratado["TP_TIPO_REDE"]== 6) &
    (df_inse_tratado["TP_LOCALIZACAO"] == 0)
].copy()

print("Quantidade de linhas:", len(df_inse_tratado))
print(
    "Quantidade de municípios únicos:",
    df_inse_tratado["CO_MUNICIPIO"].nunique()
)

df_inse_tratado.head()

Quantidade de linhas: 853
Quantidade de municípios únicos: 853

,NU_ANO_SAEB,CO_UF,SG_UF,NO_UF,CO_MUNICIPIO,NO_MUNICIPIO,TP_TIPO_REDE,TP_LOCALIZACAO,TP_CAPITAL,QTD_ALUNOS_INSE,MEDIA_INSE,PC_NIVEL_1,PC_NIVEL_2,PC_NIVEL_3,PC_NIVEL_4,PC_NIVEL_5,PC_NIVEL_6,PC_NIVEL_7,PC_NIVEL_8
56403,2023,31,MG,Minas Gerais,3136959,Juvenília,6,0,2,228,4.4254,3.26,25.15,24.13,25.74,12.28,5.66,3.34,0.43
56409,2023,31,MG,Minas Gerais,3136900,Juruaia,6,0,2,306,5.1850,0.00,3.58,13.73,21.87,27.45,22.13,11.25,NaN
56487,2023,31,MG,Minas Gerais,3136702,Juiz de Fora,6,0,2,9283,5.1931,0.36,5.39,12.72,22.98,24.92,17.76,14.11,1.76
56546,2023,31,MG,Minas Gerais,3136652,Juatuba,6,0,2,966,5.1363,0.65,5.44,13.82,23.05,25.62,19.53,10.34,1.55
56553,2023,31,MG,Minas Gerais,3136603,Nova União,6,0,2,191,5.0039,0.47,7.72,15.65,25.26,25.55,16.88,8.47,NaN

In [28]:
print(
    "Valores ausentes em MEDIA_INSE:",
    df_inse_tratado["MEDIA_INSE"].isna().sum()
)

print(
    "Percentual de valores ausentes:",
    round(df_inse_tratado["MEDIA_INSE"].isna().mean() * 100, 2),
    "%"
)

Valores ausentes em MEDIA_INSE: 0
Percentual de valores ausentes: 0.0 %

In [29]:
df_inse_final = df_inse_tratado[
    [
        "NU_ANO_SAEB",
        "CO_MUNICIPIO",
        "NO_MUNICIPIO",
        "QTD_ALUNOS_INSE",
        "MEDIA_INSE"
    ]
].copy()

df_inse_final = df_inse_final.rename(
    columns={"NU_ANO_SAEB": "ANO"}
)

df_inse_final.head()

        ANO  CO_MUNICIPIO  NO_MUNICIPIO  QTD_ALUNOS_INSE  MEDIA_INSE
56403  2023       3136959     Juvenília              228      4.4254
56409  2023       3136900       Juruaia              306      5.1850
56487  2023       3136702  Juiz de Fora             9283      5.1931
56546  2023       3136652       Juatuba              966      5.1363
56553  2023       3136603    Nova União              191      5.0039

In [30]:
df_inse_final.to_csv(
    "inse_mg_2023_tratado.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Arquivo salvo com sucesso.")

Arquivo salvo com sucesso.

In [31]:
from google.colab import files

files.download("inse_mg_2023_tratado.csv")